# Generated by Django 2.0.7 on 2018-08-11 01:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180809_2154'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='movie',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
