# Generated by Django 2.1.7 on 2019-04-04 13:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_usermovielist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermovielist',
            unique_together={('movie', 'user')},
        ),
    ]
