# Generated by Django 2.1.7 on 2019-04-05 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190404_1312'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('title', 'year')},
        ),
    ]
